# Generated by Django 5.1.7 on 2025-04-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
