# Generated by Django 5.1.7 on 2025-04-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notifications_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='link',
            new_name='page',
        ),
        migrations.AddField(
            model_name='notifications',
            name='page_item_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
