# Generated by Django 5.1.7 on 2025-05-01 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0038_alter_post_post_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelCloudinary',
            fields=[
                ('title', models.CharField(blank=True, max_length=255)),
                ('video_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reels', serialize=False, to='app.post')),
                ('reel_description', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
