# Generated by Django 5.1.7 on 2025-06-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_videocloudinary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reelcloudinary',
            name='like_count',
        ),
    ]
