# Generated by Django 5.1.7 on 2025-03-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_remove_youtube_video_data_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube_video_data',
            name='post',
        ),
        migrations.AddField(
            model_name='youtube_video_data',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
