# Generated by Django 5.1.7 on 2025-03-23 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_post_post_id_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube_video_data',
            name='id',
        ),
        migrations.AddField(
            model_name='youtube_video_data',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='video_data', serialize=False, to='app.post'),
        ),
    ]
