# Generated by Django 5.1.7 on 2025-03-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_youtube_video_data_id_youtube_video_data_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
