# Generated by Django 5.1.7 on 2025-03-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_post_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_video_data',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='video_data', serialize=False, to='app.post'),
        ),
    ]
