# Generated by Django 5.1.7 on 2025-03-23 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_youtube_video_data_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_Reels_Data',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reels_data', serialize=False, to='app.post')),
                ('reel_id', models.CharField(max_length=100)),
                ('reel_title', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField()),
                ('channel_title', models.CharField(max_length=100)),
                ('channel_image_url', models.URLField()),
                ('view_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Youtube_Reels_Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reel_id', models.CharField(max_length=100)),
            ],
        ),
    ]
