# Generated by Django 5.1.7 on 2025-03-24 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_youtube_reels_data_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_banner',
            field=models.ImageField(default='img/posts/post2.jpeg', upload_to='post_banners/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_description',
            field=models.TextField(default='lorem ipsum doler sit amet'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='app.post')),
            ],
        ),
    ]
