# Generated by Django 5.1.7 on 2025-03-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_post_post_banner_post_post_description_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_banner',
            field=models.ImageField(null=True, upload_to='img/posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='img/posts/'),
        ),
    ]
