# Generated by Django 5.1.7 on 2025-03-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_post_post_banner_alter_post_post_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
