# Generated by Django 5.1.7 on 2025-03-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
