# Generated by Django 5.1.7 on 2025-03-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_post_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_banner',
            field=models.ImageField(blank=True, null=True, upload_to='img/posts/'),
        ),
    ]
