# Generated by Django 5.1.7 on 2025-03-25 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_post_created_by'),
        ('user', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by_user',
            field=models.ForeignKey(default='asib', on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
    ]
