# Generated by Django 5.1.7 on 2025-03-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_post_created_by_user_alter_post_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by_user',
        ),
    ]
