# Generated by Django 5.1.7 on 2025-03-25 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_post_created_by_user'),
        ('user', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by_user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
            preserve_default=False,
        ),
    ]
