# Generated by Django 5.1.7 on 2025-03-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_post_created_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
    ]
