# Generated by Django 5.1.7 on 2025-03-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_youtube_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_video_data',
            name='video_description',
            field=models.TextField(default='lorem ipsum doler sit amet'),
            preserve_default=False,
        ),
    ]
