# Generated by Django 5.1.7 on 2025-03-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_youtube_video_data_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_reels_data',
            name='reel_description',
            field=models.TextField(default='lorem'),
            preserve_default=False,
        ),
    ]
