# Generated by Django 5.1.7 on 2025-04-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_youtube_reels_data_reel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_banner',
            field=models.ImageField(blank=True, default='463315330_975679841271321_5666464099814645228_n.jpg', null=True, upload_to='img/posts/'),
        ),
    ]
