# Generated by Django 5.1.7 on 2025-04-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
