# Generated by Django 5.1.7 on 2025-04-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_post_stat_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_banner',
            field=models.ImageField(blank=True, default='img/posts/463315330_975679841271321_5666464099814645228_n.jpg', null=True, upload_to='img/posts/'),
        ),
    ]
