# Generated by Django 5.1.7 on 2025-04-19 06:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_post_post_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post_stat_like',
            unique_together={('post', 'created_by')},
        ),
        migrations.DeleteModel(
            name='Youtube_Upload',
        ),
    ]
