# Generated by Django 5.1.7 on 2025-04-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_post_stat_like_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_banner',
            field=models.ImageField(blank=True, default='img/posts/post_banner_default.jpg', null=True, upload_to='img/posts/'),
        ),
    ]
