# Generated by Django 5.1.7 on 2025-04-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_banned',
            field=models.BooleanField(default=False),
        ),
    ]
