# Generated by Django 5.1.7 on 2025-04-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_user_social_fb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_social_fb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_social_twt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_social_yt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
