# Generated by Django 5.1.7 on 2025-04-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
    ]
