# Generated by Django 5.1.7 on 2025-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/ducr0o0wa/image/upload/v1746711482/default_kl0kng.jpg'),
        ),
    ]
