# Generated by Django 5.1.7 on 2025-05-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='img/profile_pics/default.jpg', upload_to='img/profile_pics/'),
        ),
    ]
