# Generated by Django 5.1.7 on 2025-08-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_status',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
