# Generated by Django 5.1.7 on 2025-04-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_post_stat_like'),
        ('event', '0002_rename_events_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='posts',
        ),
        migrations.AddField(
            model_name='event',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_post', to='app.post'),
        ),
    ]
