# Generated by Django 5.1.7 on 2025-04-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_post_post_banner'),
        ('event', '0004_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='event_post', to='app.post'),
        ),
    ]
